version: '3.7'

services:
  storefront_php:
    build:
      context: Storefront/Docker/services/php
      dockerfile: Dockerfile
    container_name: 'storefront_php'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - APP_ENV=${APP_ENV}
    volumes:
      - ${APP_PATH}:${WORKING_DIR}
      - ./Storefront/Docker/services/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
    working_dir: '${WORKING_DIR}'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  storefront_nginx:
    build:
      context: Storefront/Docker/services/nginx
      dockerfile: Dockerfile
    container_name: 'storefront_nginx'
    volumes:
      - ${APP_PATH}:${WORKING_DIR}
      - ./Storefront/Docker/services/nginx/logs:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./Storefront/Docker/services/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./Storefront/Docker/services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - storefront_php
    ports:
      - 80:80
      - 443:443

  storefront_rabbit-mq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq:rw
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/

  customer_api:
    build:
      context: Customer/Api
      dockerfile: Docker/Dockerfile
    container_name: 'customer_api'
    volumes:
      - ./Customer/Api/App:/src
      - /src/node_modules
    ports:
      - "8081:8081"
    command: ["node", "server.js"]

  newsletter_api:
    build:
      context: Newsletter/Api
      dockerfile: Docker/Dockerfile
    container_name: 'newsletter_api'
    volumes:
      - ./Newsletter/Api/App:/src
      - /src/node_modules
    ports:
      - "8082:8082"
    command: ["node", "server.js"]

  admin:
    build:
      context: Admin
      dockerfile: Docker/Dockerfile
    container_name: 'admin'
    volumes:
      - ./Admin/App:/src
      - /src/node_modules
    ports:
      - "5000:5000"
    command: ["npm", "run","serve"]

  customer_admin:
    build:
      context: Customer/Admin
      dockerfile: Docker/Dockerfile
    container_name: 'customer_admin'
    volumes:
      - ./Customer/Admin/App:/src
      - /src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST_PORT
      - HOST_URL
    ports:
      - "5001:5001"
    command: ["npm", "run", "serve"]

  newsletter_admin:
    build:
      context: Newsletter/Admin
      dockerfile: Docker/Dockerfile
    container_name: 'newsletter_admin'
    volumes:
      - ./Newsletter/Admin/App:/src
      - /src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST_PORT
      - HOST_URL
    ports:
      - "5002:5002"
    command: ["npm", "run", "serve"]

  db:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db
    environment:
      - PMA_HOST=db
volumes:
  mysql-data:

