example_api:
    path: /
    controller: App\Presentation\Api\Controller\ExampleController::index
    methods:    [GET]

admin:
    path: /admin
    controller: App\Presentation\Api\Controller\AdminController::index
    methods:    [GET]