example_api:
    path: /
    controller: App\Presentation\Api\Controller\ExampleController::index
    methods:    [GET]

payment:
    path: /api/payment/initiate
    controller: \App\Presentation\Api\Controller\InitiatePaymentController::index
    methods: [POST]
