services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\WebshopBundle\:
        resource: '../../../../WebshopBundle'
        exclude:
            - './WebshopBundle/DependencyInjection/'
            - './WebshopBundle/Entity/'
            - './WebshopBundle/Kernel.php'

    App\WebshopBundle\Presentation\Web\Controller\: # assuming you have namespace like that
        resource: '../../../Presentation/Web/Controller'
        tags: [ 'controller.service_arguments' ]

    App\WebshopBundle\Application\Registration\RegistrationCommandHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\Registration\RegistrationCommand

    App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterCommand

    App\WebshopBundle\Application\Account\QueryCustomerAccountHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\Account\QueryCustomerAccountCommand

    App\WebshopBundle\Application\CustomerSpace\GetProductCatalogHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\CustomerSpace\GetProductCatalogQuery