services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\WebshopBundle\:
        resource: '../../../../WebshopBundle'
        exclude:
            - './WebshopBundle/DependencyInjection/'
            - './WebshopBundle/Entity/'
            - './WebshopBundle/Kernel.php'

    App\WebshopBundle\Presentation\Web\Controller\: # assuming you have namespace like that
        resource: '../../../Presentation/Web/Controller'
        tags: [ 'controller.service_arguments' ]

    App\WebshopBundle\Application\CreateCustomer\CreateCustomerHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\CreateCustomer\CreateCustomerCommand

    App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterCommand

    App\WebshopBundle\Application\QueryCustomer\QueryCustomerHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\QueryCustomer\QueryCustomerCommand